[Website] ヘッダーナビゲーションの実装
FlutterKaigi/2024 pull request #180
Opened 2024-08-06 13:09 UTC by Haru-Kobayashi073

## Issue

- https://github.com/FlutterKaigi/2024/issues/167

## 説明

以下の要件に基づき、ヘッダーナビゲーションの実装を行いました。

仕様
- Websiteサイズ
  - 300px(指定がないため自己設定)スクロール後、ヘッダーが上からアニメーションで表示
- Mobileサイズ
  - Mobileでは常時表示
  - Drawerを表示させる
  - Drawerはフルスクリーン表示

## 画像 / 動画

#### Web
<img src="https://github.com/user-attachments/assets/752c97d0-89ac-4c0e-93a1-7f05cb287bcb" width="900" />

https://github.com/user-attachments/assets/0da9b836-5845-44ac-9c6c-6dfe625f5dc8

#### Mobile
<img src="https://github.com/user-attachments/assets/efb71e44-4112-4828-968e-a646d8c3b450" width="300" />
<img src="https://github.com/user-attachments/assets/6c43081f-727c-4030-97d2-d6ea5f2a86d7" width="300" />

## その他

- https://github.com/FlutterKaigi/2024/issues/150
#148 
上記二つのViewへのリンクがヘッダーにあるため、処理自体は未実装
スピーカー募集Viewへのリンク処理は実装済み
### ↑こちらの未実装セクションは、コメントアウト中

</br>
</br>

[以下のヘッダーの仕様](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=153-298&t=FHcg7n1hPSElaNrg-0)がまだ汲み取りきれていない

- スポンサー詳細ページなど、ホームページ以外の画面では、ロゴ付きのヘッダー？

<img width="757" alt="スクリーンショット 2024-08-06 22 33 10" src="https://github.com/user-attachments/assets/b485da6f-63d6-423d-9393-04f372201406">

2024-08-06 16:33 UTC, Haru-Kobayashi073 commented on apps/website/lib/ui/components/header/hamburger_menu.dart
> +    Future<void> scrollToSection(GlobalObjectKey key) async {
[メモ]
ほぼ同じ処理を他の場所でも使ってしまっている

2024-08-06 16:34 UTC, Haru-Kobayashi073 commented on apps/website/lib/ui/components/header/hamburger_menu.dart
> +        key: const GlobalObjectKey('speakerWantedSectionKey'),
[メモ]
GlobalObjectKeyの文字列のハードコーディングが気になる

2024-08-07 03:49 UTC, Haru-Kobayashi073 commented
@YumNumm 
ヘッダーナビの実装が概ね完了しましたので、お手隙の際にご確認のほどよろしくお願いいたします！
メモでコメントを残したのですが、もしよろしければ、該当箇所へのご意見をいただきたいです...!!!
他諸々もビシバシレビューくださると嬉しいです！

2024-08-10 18:29 UTC, YumNumm requested changes
@Haru-Kobayashi073 遅くなりました🙏

いくつかコメントさせていただきましたので、ご確認よろしくお願いします!

2024-08-10 18:29 UTC, YumNumm commented on apps/website/lib/ui/components/header/site_header.dart
> +}
![in-my-opinion-badge](https://img.shields.io/badge/review-imo-orange.svg)
static methodしか定義していないclassは推奨されていません。([`avoid_classes_with_only_static_members`](https://dart.dev/tools/linter-rules/avoid_classes_with_only_static_members))
(本当は、Linterに怒られるはずですが、怒られていないのでLint周りの設定間違えているかもです... 今度直します🙏)

このケースでは、[enhanced enum](https://dart.dev/language/enums#declaring-enhanced-enums)を用いるとスマートに実装できると思いました!

```suggestion
/// 各セクションへのジャンプするためのキー
enum NaviSectionKey {
  title(GlobalObjectKey('headerTitleKey')),
  speakerWanted(GlobalObjectKey('speakerWantedSectionKey')),
  sponsor(GlobalObjectKey('sponsorSectionKey')),
  staff(GlobalObjectKey('staffSectionKey')),
  ;

  const NaviSectionKey(this.key);
  final GlobalObjectKey key;
}
```

2024-08-10 18:29 UTC, YumNumm commented on apps/website/lib/ui/components/header/hamburger_menu.dart
> +        ),
![in-my-opinion-badge](https://img.shields.io/badge/review-imo-orange.svg)
Gradientや色などは、`lib/ui/theme/extension`配下に `ThemeExtension`として定義しているので、こちらに追加していただきこれを参照するような構成にしていただけると助かります! 


https://github.com/FlutterKaigi/2024/blob/076ba92c1f7b104e657f8008dd6a74177f0f8796/apps/website/lib/ui/theme/extension/theme_extension.dart#L112-L138

2024-08-10 18:29 UTC, YumNumm commented on apps/website/lib/ui/components/header/hamburger_menu.dart
> +    Future<void> scrollToSection(GlobalObjectKey key) async {
![in-my-opinion-badge](https://img.shields.io/badge/review-imo-orange.svg)

`Navigator.of(ctx).pop()`以外の部分を、`lib/common/util/scroll_to_section.dart`に切り出すとか良さそうだと思いました!

2024-08-10 18:29 UTC, YumNumm commented on apps/website/lib/ui/components/header/site_header.dart
> +        onPressed: () => Scaffold.of(context).openEndDrawer(),
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
`Scaffold.of(context).openEndDrawer()`という関数が用意されているのは知りませんでした! 
Niceです!

2024-08-11 05:33 UTC, Haru-Kobayashi073 commented
@YumNumm 
レビューありがとうございます！
修正完了いたしましたので、ご確認のほどよろしくお願いします！

2024-08-11 05:34 UTC, YumNumm approved these changes
対応ありがとうございます! 
全体的に丁寧な実装がされていて とても読みやすかったです! 

もし可能であれば、`Staff`と`Sponsor`のセクションだけコメントアウトしてもらえると助かります! (このままマージしていただいて 別PR対応でもOKです!)

![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8251349)

2024-08-11 05:48 UTC, Haru-Kobayashi073 commented
@YumNumm 
嬉しいです！！！
未実装のセクションに関しては、コメントアウトし、プッシュ完了しました！

2024-08-11 05:59 UTC, YumNumm commented
ありがとうございます! LGTMです!
爆速対応助かります!
マージお願いします!

2024-08-11 06:19 UTC, merged