【App】スポンサー詳細画面を作成しました
FlutterKaigi/2024 pull request #195
Opened 2024-08-23 08:39 UTC by TK-Guitar

## Issue

- https://github.com/FlutterKaigi/2024/issues/29

## 説明

スポンサーのUIをタップするとスポンサーの詳細情報が出るボトムシートを作成しました。

## 画像 / 動画

https://github.com/user-attachments/assets/a8a1acb8-a282-4650-8e13-93b801e79fde

## その他

以下のFigmaを参考にしました
https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=914-3641&t=eE59CYaXIPrmZl3t-0

2024-08-23 08:41 UTC, TK-Guitar commented on packages/app/features/about/lib/src/ui/sponsors/sponsors_page.dart
ボトムシートのサンプルをわかりやすくするためにダミーテキストを変更しました

2024-08-25 05:19 UTC, Kurogoma4D requested changes

2024-08-25 13:21 UTC, TK-Guitar commented on packages/app/features/about/lib/src/gen/l10n/l10n.dart
> +  String get seeMore;
すみません、対応しました🙏
[8e9a8ed](https://github.com/FlutterKaigi/2024/pull/195/commits/8e9a8edd201336e3e3d309a56e8b8bdf0fc0fa59)

2024-08-25 13:28 UTC, TK-Guitar commented on packages/app/features/about/lib/src/ui/sponsors/sponsors_item.dart
> +                            final uri = Uri.parse(_sponsor.sponsorLinkUrl);
了解です。
エラーハンドリングの対応しました。
[7b83139](https://github.com/FlutterKaigi/2024/pull/195/commits/7b83139b9268de25cf61224154a0d6a3b624c214)

2024-08-25 13:48 UTC, TK-Guitar commented on packages/app/features/about/lib/src/ui/sponsors/sponsors_item.dart
> +                      ),
新たなやり方を教えてくれてありがとうございます🙇
対応しました！
[d262766](https://github.com/FlutterKaigi/2024/pull/195/commits/d262766c32cb59703440d66bf4ba334ba37aece4)
[5523a01](https://github.com/FlutterKaigi/2024/pull/195/commits/5523a01254fcd30916e25fd6880ca18c575e6bf7)

2024-08-25 13:53 UTC, TK-Guitar commented on packages/app/features/about/lib/src/ui/sponsors/sponsors_item.dart
> +                      ),
不要な外部パッケージも削除しました
[b57a00c](https://github.com/FlutterKaigi/2024/pull/195/commits/b57a00ccc5ec059cf904a35c2ceb6489d932e2fd)

2024-08-25 14:14 UTC, blendthink approved these changes
LGTM です！
ご対応ありがとうございます！

2024-08-25 14:39 UTC, merged