[website] スタッフ一覧の実装
FlutterKaigi/2024 pull request #372
Opened 2024-10-20 12:48 UTC by YumNumm

## Issue

- Closes https://github.com/FlutterKaigi/2024/issues/150

## 説明

## 画像 / 動画

| Before | After | Design |
|-|-|-|
| | | |

## その他

2024-10-20 18:16 UTC, blendthink approved these changes
コメントしているものの、問題ないかと思いますのでLGTMです！
ご対応ありがとうございます！

2024-10-20 18:16 UTC, blendthink commented on apps/website/lib/feature/staff/ui/staff_view.dart
> +  /// スタッフカードが横に何枚入るかを計算する
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
❤️

2024-10-20 18:16 UTC, blendthink commented on apps/website/lib/ui/components/sns_icon.dart
> +    );
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
❤️

2024-10-20 18:16 UTC, blendthink commented on apps/website/lib/core/extension/iterable_ex.dart
> +// cf. https://github.com/dart-lang/sdk/issues/49900#issuecomment-1236913547
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
❤️

2024-10-20 18:16 UTC, blendthink commented on apps/website/lib/feature/staff/ui/components/staff_card.dart
> +  static double width = 220;
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
iPhone 15 Pro で１つだけ表示されるようになっているので、個人的にはもう少し小さくして2つ表示されるようにしてしまっても良いかもと思いました。(マージンの調整でも良いかも？)

![image](https://github.com/user-attachments/assets/5078261c-99dd-4bb5-bf1e-7a117dee163f)

2024-10-20 18:52 UTC, YumNumm commented on apps/website/lib/feature/staff/ui/components/staff_card.dart
> +  static double width = 220;
モバイルでこの表示だとちょっと辛いですね…
モバイルサイズの時はPaddingを小さくするようにしましょうか

明日修正します!

2024-10-22 13:10 UTC, blendthink requested changes
#377 の影響で動かなくなってしまったところがあると思うので、念の為 Request changes しておきます 🙏

2024-10-23 10:12 UTC, YumNumm commented on apps/website/lib/feature/staff/ui/staff_view.dart
> +import 'package:conference_2024_website/feature/staff/data/staff_notifier.dart';
:check:

2024-10-23 14:37 UTC, YumNumm commented on apps/website/lib/feature/staff/ui/components/staff_card.dart
> +  static double width = 220;
@blendthink 
余白を調整してみましたが、いかがでしょうか?

![image](https://github.com/user-attachments/assets/3c351c05-fc71-4ecf-b1b8-95aafacc4336)

2024-10-23 14:51 UTC, blendthink approved these changes
LGTM です！
ご対応ありがとうございます！

2024-10-23 14:51 UTC, merged