[data]: セッション情報の投入
FlutterKaigi/2024 pull request #401
Opened 2024-10-23 16:43 UTC by YumNumm

## Issue

- Closes NONE

## 説明
- セッションデータを投入します

2024-10-26 03:08 UTC, Kurogoma4D commented on packages/common/data/supabase/seed.sql
> +  ('f6ee9501-0698-44ea-ad21-eb051ee94a8e', 'B');
（まだマージされてなかったので）
セッションルーム名更新されたので、こちらも変更したほうが良さそうです！

- `A Dash`
- `B Dash`

2024-10-26 16:01 UTC, blendthink commented on packages/common/data/supabase/seed.sql
> +    'Flutterアプリで可用性を向上させたFeatureFlagの運用戦略とその方法',
「キャッシュレス決済アプリでのFlutterの部分的採用から全面採用まで」の代わりに「Flutterアプリで可用性を向上させたFeatureFlagの運用戦略とその方法」が入ってしまっていますので、修正お願いします！
https://docs.google.com/spreadsheets/d/1BwLLwxmg9QF2Yu3qHL0C9ziXs9FtUkjgtws09gQAdzk/edit?gid=1948292032#gid=1948292032&range=C44

2024-10-26 16:02 UTC, blendthink commented on packages/common/data/supabase/seed.sql
> +    'Flutterアプリで可用性を向上させたFeatureFlagの運用戦略とその方法',
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも削除お願いします 🙏

2024-10-28 15:10 UTC, YumNumm commented on packages/common/data/supabase/seed.sql
> +  ('f6ee9501-0698-44ea-ad21-eb051ee94a8e', 'B');
指摘ありがとうございます🙏

fixed at e132266e6e2e7cdcf539b4616191c7de4202d525

2024-10-29 04:33 UTC, blendthink requested changes
@YumNumm 
コメントしましたので、ご確認お願いします🙏

2024-10-29 04:33 UTC, blendthink commented on packages/common/data/supabase/seed.sql
> +    '## スポンサー名 株式会社出前館  ## 概要 本セッションでは、出前館アプリにおけるFlutterアプリ設計、そしてそれらを支えるCICD環境について述べます。  セッション前半では出前館アプリのアプリ設計についてお話しします。 出前館アプリのフォルダ構成やAsset Management、そしてState Managementについてお話しします。 現在出前館では、提供するすべて
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
改行入れてあげた方が良いかもです、、！

2024-10-29 04:33 UTC, blendthink commented on packages/common/data/supabase/seed.sql
> +    '## 概要
![must-badge](https://img.shields.io/badge/review-must-red.svg)
内容間違えているようですので修正お願いします！
https://fortee.jp/flutterkaigi-2024/proposal/efaab44f-3ceb-4fe4-bab5-ff53db5f81ff

2024-10-29 14:30 UTC, blendthink commented
@YumNumm 
#425 で指摘内容 + α で修正していますので、ご確認お願いします🙏

2024-10-29 14:43 UTC, blendthink approved these changes
LGTM です！

2024-10-29 14:43 UTC, merged