[ticket_web] 前夜祭の記述を追加
FlutterKaigi/2024 pull request #442
Opened 2024-10-31 18:05 UTC by YumNumm

## 説明

- タイトルの通りです

2024-11-01 13:15 UTC, blendthink requested changes
@YumNumm 
２点コメントしましたのでご確認お願いします 🙏

2024-11-01 13:15 UTC, blendthink commented on apps/ticket_web/lib/core/i18n/strings.i18n.json
> +          "- **前夜祭への参加**: 2024/11/20(水)に開催する前夜祭へ参加頂けます([詳細はこちら](https://medium.com/flutterkaigi/flutterkaigi-2024%E5%89%8D%E5%A4%9C%E7%A5%AD%E3%82%92%E9%96%8B%E5%82%AC%E3%81%97%E3%81%BE%E3%81%99-5e7f
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
`)` が１つ足りないかもしれません、、！
```suggestion
          "- **前夜祭への参加**: 2024/11/20(水)に開催する前夜祭へ参加頂けます([詳細はこちら](https://medium.com/flutterkaigi/flutterkaigi-2024%E5%89%8D%E5%A4%9C%E7%A5%AD%E3%82%92%E9%96%8B%E5%82%AC%E3%81%97%E3%81%BE%E3%81%99-5e7ff7ba3947))",
```

2024-11-01 13:15 UTC, blendthink commented on apps/ticket_web/lib/pages/home/components/ticket_cards/personal_sponsor_ticket_card.dart
>              MarkdownBody(
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`onTapLink` の実装が漏れていそうですので、ご確認お願いします 🙏 
```dart
MarkdownBody(
  data:
      i18n.homePage.tickets.personalSponsor.description.join('\n'),
  styleSheet: MarkdownStyleSheet.fromTheme(theme).copyWith(
    p: textTheme.bodyLarge?.copyWith(
      color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
    ),
  ),
  softLineBreak: true,
  onTapLink: (text, href, title) async {
    if (href == null) {
      return;
    }
    unawaited(
      launchUrlString(href),
    );
  },
),
```

2024-11-01 16:49 UTC, YumNumm commented on apps/ticket_web/lib/core/i18n/strings.i18n.json
> +          "- **前夜祭への参加**: 2024/11/20(水)に開催する前夜祭へ参加頂けます([詳細はこちら](https://medium.com/flutterkaigi/flutterkaigi-2024%E5%89%8D%E5%A4%9C%E7%A5%AD%E3%82%92%E9%96%8B%E5%82%AC%E3%81%97%E3%81%BE%E3%81%99-5e7f
細かいところ ありがとうございます🙇
すっかり見落としていました🙇

2024-11-01 16:53 UTC, YumNumm commented on apps/ticket_web/lib/pages/home/components/ticket_cards/personal_sponsor_ticket_card.dart
>              MarkdownBody(
b6b9a72ba0f0188538e6fd4fd3dfa66375147f03 
こちらで修正しました

2024-11-02 00:25 UTC, blendthink approved these changes
@YumNumm 
LGTM です！、、が、自動生成で差分が出て CI が失敗しているのでご確認お願いします🙏

2024-11-02 00:25 UTC, merged